version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootpassword
      - POSTGRES_DB=mytodoapp
    volumes:
      - my-todo-app_postgres-data:/var/lib/postgresql/data
    networks:
      - my-todo-app_default

  nextjs:
    image: node:18
    container_name: nextjs
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=postgresql://root:rootpassword@postgres:5432/mytodoapp
    command: ["sh", "-c", "npx prisma migrate deploy && npm install && npm test && npm run build && npm run start"]
    networks:
      - my-todo-app_default
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.next:/usr/share/nginx/html
      - ./public:/usr/share/nginx/public
    ports:
      - "80:80"
    networks:
      - my-todo-app_default
    depends_on:
      - nextjs

volumes:
  my-todo-app_postgres-data:

networks:
  my-todo-app_default:
    driver: bridge
